version: 2.1
workflows:
  workflow:
    jobs:
      - test

jobs:
  test:
    docker:
      - image: circleci/node@10.16

    steps:
      - checkout

      - run: yarn install
      - run: yarn test
